### ISSUE TITLE
I get a gazebo error when running system_garage.launch

### ISSUE THREAD

**Issue by charon-cheung** [HongbiaoZ/autonomous_exploration_development_environment#4]
Error:   Could not parse visual element for Link [base_origin]
problem is in <node pkg="gazebo_ros" type="spawn_model" name="spawn_robot" args="-urdf -param /robot_description -model robot"/>

Is there something wrong with robot.urdf.xacro ?

**Comment by maxibooksiyi** [comment]
how to solve it?
